### ISSUE TITLE
python file naming

### ISSUE THREAD

**Issue by rlkennedyreid** [mynamesjack/higher_or_lower#1]
Not an issue for these sorts of small CLI programs, but a good thing to keep in mind in future:

Python source code files generally should only have lowercase characters, and never spaces. Underscores can be used to separate words if it helps readability.

[More here](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) if you're interested. A 'Module' is basically one python source file. A 'package' is a collection of source files, but that's a whole other topic!

Overall, spaces in all filenames - whether it's data files, source files, whatever - should always be avoided, for a number of reasons. Dashes and underscores are the best alternative

**Comment by mynamesjack** [comment]
Made some changes- Thank you! It's just a force of habit, I'll get used to it.
